from building import *
import os
import rtconfig


cwd = GetCurrentDir()

# add general drivers
src = []
path =  [cwd]

src += Glob('mnt.c')

group = DefineGroup('filesystem', src, depend = ['BSP_USING_FS'], CPPPATH = path)

Return('group')
