from building import *
import os

cwd     = GetCurrentDir()

# Add all subdirectories to include path
path = []
path += [cwd]
path += [cwd + '/ui', cwd + '/webnet', cwd + '/iot']

src = Glob('*.c')

group = DefineGroup('xiaozhi', src, depend = [''], CPPPATH = path)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
